### ISSUE TITLE
没编译成功...

### ISSUE THREAD

**Issue by smarttang** [ckane/yaranids#1]
```
[root@localhost yaranids]# sh buildit.sh 
yaranids.c:3:10: fatal error: 'nids.h' file not found
#include <nids.h>
         ^
1 error generated.
[root@localhost yaranids]
```

**Comment by ckane** [comment]
What Linux distribution are you using? It looks like the libnids headers are not installed.

If Debian-like (Ubuntu, Kali, etc.), an example where `foo.c` is the following file:
```c
#include <nids.h>

int
main(int argc, char **argv) {
        return 0;
}
```

Trying it with bare system:
```bash
cc foo.c 
foo.c:1:10: fatal error: nids.h: No such file or directory
    1 | #include <nids.h>
      |          ^~~~~~~~
compilation terminated.
```

Trying it after installing `libnids-dev` and `libpcap-dev`:
```bash
apt install -y libnids-dev libpcap-dev
.... install proceeds .....

cc foo.c
(succeeds produces a.out)
./a.out
```

**Comment by ckane** [comment]
I think for RedHat / CentOS / Amazon AMI, this would use `yum` and be:
```bash
yum install libpcap-devel libnids-devel
```

**Comment by amiwinter** [comment]
Please remove me from your mailing list..
I was added by accident (I believe)

Best regards

**Comment by smarttang** [comment]
THX...：）
